version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - bookclub-network

  api:
    build: .
    container_name: bookclub-api
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - bookclub-network
    environment:
      - MONGO_URL=mongodb://db:27017/

networks:
  bookclub-network:
    driver: bridge
