version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/booksdb
