version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://db:27017/booksdb

volumes:
  mongo-data: