version: '3.8'

services:
  db:
    image: mongo
    container_name: bookclub-api-db
    ports:
      - 27017:27017

  web:
    build:
      context: .
    image: bookclub-api
    container_name: bookclub-api
    ports:
      - 5001:5001
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017
